# Generated by Django 5.2.7 on 2025-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italian_cuisine_app', '0002_alter_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
